export type ExperienceSeat = {
  id: string;
  index: string;
  org: string;
  short: string;
  role: string;
  dates: string;
  place: string;
  figure: string;
  figureLabel: string;
  line: string;
  note: string;
  did: string[];
  channels: string[];
  kind: "product" | "seat";
  featured?: boolean;
};

export const EXPERIENCE_SEATS: ExperienceSeat[] = [
  {
    id: "mentionx",
    index: "00",
    org: "MentionX",
    short: "MENTIONX",
    role: "Founder",
    dates: "Building now",
    place: "Berlin · Independent",
    figure: "AEO / GEO",
    figureLabel: "AI discovery intelligence",
    line: "Ask the models the questions buyers already type.",
    note: "Built independently because the discovery layer moved faster than the measurement layer.",
    did: [
      "Built MentionX as an independent product so brands can see whether ChatGPT or Gemini name them, omit them, or recommend a competitor.",
      "Asks buyer-style prompts against AI engines and turns the answers into a dated file: mention rate, recommendation rate, competitors, cited sources.",
      "Gives teams a scoreboard for AEO and GEO that sits beside Ads, Search Console and the CRM — not a renamed SEO package.",
    ],
    channels: ["AEO", "GEO", "ChatGPT", "Gemini", "Buyer prompts"],
    kind: "product",
    featured: true,
  },
  {
    id: "eqs",
    index: "01",
    org: "EQS Group",
    short: "EQS",
    role: "Senior Performance Marketing Manager",
    dates: "June 2025 — present",
    place: "Berlin",
    figure: "Full funnel",
    figureLabel: "paid · SEO · AEO · lifecycle · CRO",
    line: "Paid to pipeline. One owner.",
    note: "Owns multi-market B2B growth. Connects acquisition to pipeline quality, funnel conversion, and revenue — HubSpot and Salesforce as the system of record, not the slide.",
    did: [
      "Run and optimise paid acquisition across Google Ads, LinkedIn and Microsoft Ads.",
      "Tighten campaign structure around commercial intent, audience relevance and landing-page alignment.",
      "Build brand versus non-brand reporting through HubSpot and Looker Studio.",
      "Contribute to SEO briefing, technical priority, internal linking and AI-search visibility.",
      "Work across product marketing, content, sales and marketing operations so channel work survives the sales handoff.",
    ],
    channels: ["Google Ads", "LinkedIn", "Microsoft Ads", "HubSpot", "Looker", "SEO", "AEO"],
    kind: "seat",
  },
  {
    id: "thinkproject",
    index: "02",
    org: "Thinkproject",
    short: "THINKPROJECT",
    role: "Growth Marketing Lead",
    dates: "September 2024 — May 2025",
    place: "Berlin",
    figure: "Global ads",
    figureLabel: "Google Ads · Bing · enterprise markets",
    line: "Pipeline quality. Not click volume.",
    note: "Scaled paid demand with the constraint that mattered: pipeline quality and CAC, not click volume.",
    did: [
      "Lead paid demand for an enterprise construction-software business across global markets.",
      "Build acquisition workflows that sales could actually run — not a lead dump.",
      "Hold spend to pipeline quality and CAC instead of click volume.",
      "Tighten message, audience and buyer-journey fit for a complex enterprise product.",
    ],
    channels: ["Google Ads", "Bing", "Enterprise demand", "CAC", "Pipeline"],
    kind: "seat",
  },
  {
    id: "zalando",
    index: "03",
    org: "Zalando",
    short: "ZALANDO",
    role: "Growth Marketing Manager, B2B",
    dates: "June 2022 — August 2024",
    place: "Berlin",
    figure: "B2B growth",
    figureLabel: "paid search · audience tests · funnel",
    line: "B2B inside a consumer giant.",
    note: "In-house B2B at a consumer giant. Messaging, relevance, and revenue support with sales and comms — not a brand campaign wearing a demand-gen badge.",
    did: [
      "Own B2B performance marketing across digital channels inside Zalando.",
      "Manage daily budgets and optimise for CPL and conversion, not vanity reach.",
      "Read user behaviour to brief content and SEO — then report the findings to management.",
      "Work with marketing and sales so B2B messaging stayed commercially useful at consumer scale.",
    ],
    channels: ["Paid search", "CRO", "SEO", "Audience tests", "Sales + comms"],
    kind: "seat",
  },
  {
    id: "madras",
    index: "04",
    org: "MadrasMarketers",
    short: "MADRASMARKETERS",
    role: "Founder, growth consultant",
    dates: "March 2017 — January 2022",
    place: "Chennai",
    figure: "0 → 1",
    figureLabel: "Appsmith · Zetwerk · Airbase · Argonaut · Freshflows",
    line: "0→1 with founders in the room.",
    note: "Built acquisition from scratch with founders: positioning, first channels, first loops. The work was getting a company from traction to a system.",
    did: [
      "Found the practice and later led a team across paid, SEO, analytics and conversion.",
      "Sit with founders and stand up the first acquisition system: positioning, channels, measurement.",
      "Partner with B2B SaaS companies including Appsmith, Zetwerk, Airbase, Argonaut and Freshflows.",
      "Set analytics, paid and SEO so early traction could become a repeatable engine.",
    ],
    channels: ["0→1 GTM", "Paid", "SEO", "Analytics", "Founder rooms"],
    kind: "seat",
  },
  {
    id: "gofrugal",
    index: "05",
    org: "GoFrugal",
    short: "GOFRUGAL",
    role: "Growth Hacker",
    dates: "November 2018 — July 2020",
    place: "Chennai",
    figure: "INR 40M",
    figureLabel: "from the online organic programme",
    line: "₹40M organic. On a ledger.",
    note: "Led paid and organic with a revenue target attached. The organic number is the one that survived contact with a ledger.",
    did: [
      "Lead a team of six across Google Ads, Gartner and G2, landing pages, SEO and reporting.",
      "Run paid and organic against a revenue target — not a traffic target.",
      "Build the online organic programme that put INR 40M on the ledger.",
      "Connect POS software to how real retailers and restaurants actually find and adopt it.",
    ],
    channels: ["Google Ads", "SEO", "G2", "Gartner", "Landing pages"],
    kind: "seat",
  },
  {
    id: "kissflow",
    index: "06",
    org: "Kissflow",
    short: "KISSFLOW",
    role: "Digital Marketing Specialist",
    dates: "November 2017 — October 2018",
    place: "Chennai",
    figure: "Google Ads",
    figureLabel: "primary revenue driver",
    line: "Rebuild the account. Lower the CPA.",
    note: "Kissflow is a low-code platform. Google Ads was the primary revenue driver. The work was to take the account apart and put it back together.",
    did: [
      "Own Google Ads as the primary revenue channel for a low-code B2B SaaS product.",
      "Overhaul account structure and campaigns so spend mapped to qualified demand.",
      "Lift qualified leads and bring CPA down by rebuilding how the account was run.",
      "Keep paid search honest against a product that sells process, not a consumer click.",
    ],
    channels: ["Google Ads", "B2B SaaS", "Lead quality", "CPA"],
    kind: "seat",
  },
  {
    id: "zarget",
    index: "07",
    org: "Zarget (Freshworks / Freshmarketers)",
    short: "ZARGET",
    role: "Head of Digital Marketing",
    dates: "June 2016 — November 2017",
    place: "Chennai",
    figure: "$250k ARR",
    figureLabel: "competitor campaign, measured on revenue",
    line: "$250k ARR. Revenue, not reach.",
    note: "First marketing hire at Zarget, a CRO platform later acquired by Freshworks. Freshmarketers sat in that same Freshworks growth story.",
    did: [
      "Join as the first marketing hire and stand paid up from zero — Google, Bing, LinkedIn, Facebook, Quora, content syndication, SEO.",
      "Build the competitor campaign that put $250k ARR on the board, measured on revenue.",
      "Scale leads 35× and help take the company through the Freshworks acquire.",
      "Run digital like a CRO product should be sold: proof, not theatre.",
    ],
    channels: ["Google Ads", "Bing", "LinkedIn", "Meta", "SEO", "CRO"],
    kind: "seat",
  },
  {
    id: "sulekha",
    index: "08",
    org: "Sulekha",
    short: "SULEKHA",
    role: "Senior Digital Marketing Specialist",
    dates: "June 2015 — June 2016",
    place: "Chennai",
    figure: "International",
    figureLabel: "USA · Canada · Australia",
    line: "Local services. International accounts.",
    note: "India’s largest digital platform for local services. The seat was performance, not brand.",
    did: [
      "Drive revenue through performance campaigns for local-service demand.",
      "Run international accounts across the USA, Canada and Australia on Google, Meta and LinkedIn.",
      "Hit ambitious acquisition targets with spend that had to explain itself.",
      "Mentor and train new hires on Google Ads — the craft, not the dashboard tour.",
    ],
    channels: ["Google Ads", "Meta", "LinkedIn", "International", "Mentoring"],
    kind: "seat",
  },
  {
    id: "o3m",
    index: "09",
    org: "O3M Directional Marketing",
    short: "O3M",
    role: "Search Engine Associate",
    dates: "June 2014 — June 2015",
    place: "Chennai",
    figure: "65+ clients",
    figureLabel: "50 local · 15 international",
    line: "Premier partner. Client rooms.",
    note: "Google and Meta official premier partner. The work was other people’s revenue, every week.",
    did: [
      "Plan and optimise Google Ads and Meta Ads for 50+ local and 15+ international clients.",
      "Sit with clients, read the account, and change the work — not send a slide.",
      "Tailor each book of work to ROI, branding or lead gen, depending on the brief.",
      "Learn how an agency premier partner actually has to perform.",
    ],
    channels: ["Google Ads", "Meta Ads", "Client rooms", "ROI"],
    kind: "seat",
  },
  {
    id: "csscorp",
    index: "10",
    org: "CSS Corp",
    short: "CSS CORP",
    role: "Ad Trafficking Analyst",
    dates: "May 2012 — May 2014",
    place: "Chennai",
    figure: "Ad ops",
    figureLabel: "P&G · Fox · Sky · Disney",
    line: "The first seat. Delivery first.",
    note: "The start of the 13 years. Trafficking for Operative. Forecast the impressions. Make the campaign land.",
    did: [
      "Traffic display and video campaigns for brands including P&G, Fox, Sky and Disney.",
      "Work inside Operative with DoubleClick, MoPub, PubMatic, Freewheel and Display & Video 360.",
      "Forecast impressions and keep delivery honest against the booked plan.",
      "Learn ad ops from the pipe: if it does not deliver, nothing else matters.",
    ],
    channels: ["DoubleClick", "DV360", "Freewheel", "MoPub", "PubMatic"],
    kind: "seat",
  },
];

export const MENTIONX_STORY = {
  kicker: "LOCKUP 03 / THE BUILD",
  title: "MENTIONX",
  url: "https://mentionx.ai",
  urlLabel: "MentionX.ai",
  what: {
    heading: "What it is",
    lines: [
      "An AI discovery intelligence product.",
      "It asks the models the questions buyers already type — then files what comes back.",
      "Not a ranking report. A dated view of whether you are named, omitted, or replaced.",
    ],
  },
  does: {
    heading: "What it does",
    lines: [
      "You put in a brand URL. MentionX reads the site, the market, the competitors.",
      "It writes buyer-style prompts and runs them through ChatGPT, Gemini and the engines that follow.",
      "You get visibility, mentions, recommendation rate, competitor substitution and the sources the models cite.",
      "Then a short list of AEO and GEO actions — what to fix first.",
    ],
  },
  why: {
    heading: "Why I built it independently",
    lines: [
      "I started MentionX because the discovery layer was moving faster than the measurement layer.",
      "Teams can still read Google Ads, Search Console and the CRM. They cannot see whether an AI system would recommend them.",
      "Agencies were going to sell “AI SEO” as a renamed package. I wanted a product with a scoreboard.",
      "AI answers move. They vary by prompt, market, engine and time. The work is to make the pattern visible so a team can decide.",
      "So I built it myself. Independently. In Berlin. While still in the seats.",
    ],
  },
} as const;

export function seatById(id: string) {
  return EXPERIENCE_SEATS.find((seat) => seat.id === id);
}
